### ISSUE TITLE
Uso de Numpy

### ISSUE THREAD

**Issue by rubens-bolgheroni** [theyujisamfull/EP-Google#1]
Questionei o professor sobre o uso de Numpy semana passada, ele falou que tudo bem, mas acho que desde as funções principais sejam implementadas, mas aí surgiu a dúvida se  coisas básicas como multiplicação de matrizes entram como funções principais, ou seria necessário implementá-las também. Alguém chegou a questioná-lo mais precisamente sobre isso?

**Comment by guilhermefgs** [comment]
Não conversei com o professor. Mas acho que as funções que seriam utilizadas do numpy já foram implementadas.
